<?php
    /** @var $block \MageSuite\ProductPositiveIndicators\Block\RecentlyBought\Product */
    $recentlyBought = $block->getRecentlyBoughtInfo();
?>

<?php if ($recentlyBought['active']) : ?>
    <?php
        $customersWording = $recentlyBought['sum'] > 1 ? 'customers' : 'customer';
        $daysWording = $recentlyBought['order_period'] > 1 ? 'days' : 'day';
    ?>

    <?= __("%1 bought this product within last %2", $recentlyBought['sum'].' '.$customersWording, $recentlyBought['order_period'].' '.$daysWording); ?>
<?php endif; ?>
