<?php
/** @var \MageSuite\ProductPositiveIndicators\ViewModel\PopularIndicator\TileBadgeShower $viewModel */
/** @var \Magento\Framework\View\Element\Template $block*/
$viewModel = $block->getViewModel();
?>
<script type="text/x-magento-init">
    {
        "isCurrentPageCategory": <?=$viewModel->isCurrentPageCategory() ? 'true' : 'false'?>,
        "currentCategoryId": <?=$viewModel->getCurrentCategoryPageId() ?? 'null' ?>
    }
</script>
