<?php
/** @var $block \MageSuite\ProductPositiveIndicators\Block\ExpectedDelivery\Product */
$isEnabled = $block->isEnabled();

if ($isEnabled) {

    //this value depends on actual time and we should use js to get actual time
    $canSendToday = $block->getMaxTimeToday() && $block->getMaxTimeToday() < time();

    //display one of these <p>. If $canSendToday returns true, display the first one. If $canSendToday returns false, return the second one.
    ?><p style="display:none"><?= /* @noEscape */ sprintf(__('You can get this product on %s (%s) if you buy it now!'), $block->getShipDayName(), $block->getShipDayTime()); ?></p><?php
    ?><p style="display:none"><?= /* @noEscape */ sprintf(__('You can get this product on %s (%s) if you buy it now!'), $block->getNextShipDayName(), $block->getNextShipDayTime()); ?></p><?php
}
?>
